Feat/add unit testing
dashlog/core pull request #56
Opened 2023-06-30 15:51 UTC by abbesAlexandre

test: adding tests for plugins files : nodescure.ts, scorecard.ts

2023-06-30 16:16 UTC, PierreDemailly requested changes

2023-06-30 16:16 UTC, PierreDemailly commented on test/scorecard.spec.ts
> +import { MockAgent, setGlobalDispatcher } from "undici";
```suggestion
// Import Third-party Dependencies
import { MockAgent, setGlobalDispatcher } from "undici";

// Import Internal Dependencies
import { execute } from "../src/plugins/scorecard";
```
```

2023-06-30 16:16 UTC, PierreDemailly commented on test/scorecard.spec.ts
> +import { MockAgent, setGlobalDispatcher } from "undici";
Same in `nodesecure.spec.ts`

2023-06-30 16:16 UTC, PierreDemailly commented on test/nodesecure.spec.ts
> +import { test, after, describe, it } from "node:test";
```suggestion
// Import Node.js Dependencies
import { test, after, describe, it } from "node:test";
```

2023-06-30 16:16 UTC, PierreDemailly commented on test/nodesecure.spec.ts
> +  test("should return void", async() => {
```suggestion
  it("should return void", async() => {
```

I think we can use only `it` and remove `test` from the imports ?

2023-06-30 16:16 UTC, PierreDemailly commented on test/nodesecure.spec.ts
Maybe we can move theses to files in `/test/plugins/` ?

2023-06-30 20:55 UTC, PierreDemailly approved these changes

2023-07-08 13:54 UTC, fraxken approved these changes

2023-07-08 13:54 UTC, merged