Detect node test runner
dashlog/core pull request #89
Opened 2024-08-05 17:17 UTC by fabnguess

2024-08-05 18:33 UTC, PierreDemailly reviewed
Could you add tests for `getTestFrameworkName` ?

2024-08-05 18:33 UTC, PierreDemailly commented on src/utils/getTestFrameworkName.ts
> +function IsNodeTestingUsed() {
Functions should be camelCase

```suggestion
function isNodeTestingUsed() {
```
or
```suggestion
function isNodeTestRunnerUsed() {
```

2024-08-05 18:33 UTC, PierreDemailly commented on src/utils/getTestFrameworkName.ts
> +  const nodeTestRegex = /(?:node\s+--test|tsx)/;
Use file const prefixed with `k` (`kNodeTestRunnerRegex`)

2024-08-05 18:33 UTC, PierreDemailly commented on src/utils/getTestFrameworkName.ts
> +import path from "path";
```suggestion
import fs from "node:fs";
import path from "node:path";
```
(This should even be removed as we will not parse package.json again)

2024-08-05 18:34 UTC, PierreDemailly commented on src/utils/getTestFrameworkName.ts
> +  const packageJsonPath = path.join(process.cwd(), "package.json");
We should not parse package.json again, scripts should be accessible from here:
https://github.com/dashlog/core/blob/6159d526453b209542bbc7df434d3637f4c34f1c/src/services/repository.ts#L155-L164

2024-08-05 21:22 UTC, fraxken requested changes

2024-08-05 21:22 UTC, fraxken commented on src/utils/getTestFrameworkName.ts
> +  }
We don't need that, here you'r checking the Node.js version currently running by the dashlog process (not the Node.js version supported by the project we are scanning)

2024-08-05 22:35 UTC, fraxken approved these changes

2024-08-06 08:27 UTC, PierreDemailly commented on src/utils/getTestFrameworkName.ts
> +export function getTestFrameworkName(packageJson : PackageJSON) : string {
```suggestion
export function getTestFrameworkName(packageJson: PackageJSON): string {
```

2024-08-06 11:49 UTC, PierreDemailly approved these changes

2024-08-06 21:14 UTC, fraxken approved these changes

2024-08-06 21:15 UTC, merged

2024-08-06 21:15 UTC, fraxken commented
@allcontributors please add @fabnguess for code